# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfoutdated < Formula
  desc "Detect outdated Terraform modules and providers with breaking change analysis"
  homepage "https://github.com/AnassKartit/tfoutdated"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.2.0/tfoutdated_0.2.0_darwin_amd64.tar.gz"
      sha256 "36fe265a5b4bbbf8796e5588cb229b607d252d5940d18a7e2cff47b9c2af3f77"

      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.2.0/tfoutdated_0.2.0_darwin_arm64.tar.gz"
      sha256 "6c5c41fe638135471dcdf1a44c7623ac764be5b2e5b834a9d08e2f630d7ce318"

      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.2.0/tfoutdated_0.2.0_linux_amd64.tar.gz"
      sha256 "67a305762649fcd4052aa86c1e111d520b63f9117ad2cd413baf45bb270b96d2"
      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.2.0/tfoutdated_0.2.0_linux_arm64.tar.gz"
      sha256 "77cf6e797708cb8417e80b9272e324af0067cf6be3b394288e014d98164f0765"
      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfoutdated version")
  end
end
