# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfoutdated < Formula
  desc "Detect outdated Terraform modules and providers with breaking change analysis"
  homepage "https://github.com/AnassKartit/tfoutdated"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.2.0/tfoutdated_0.2.0_darwin_amd64.tar.gz"
      sha256 "1d0be078417c9b8606e691809283ecfd0271ed27c84192a8b8289736a8e0f98d"

      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.2.0/tfoutdated_0.2.0_darwin_arm64.tar.gz"
      sha256 "edc06e70f0a5b65dd27a19465d190efddc20557eebddde7c76fb884809fe5d47"

      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.2.0/tfoutdated_0.2.0_linux_amd64.tar.gz"
      sha256 "59ec688915650413269f0e9c1a92bd7d50a16a8786712a0cfa5dbb7817c8314c"
      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.2.0/tfoutdated_0.2.0_linux_arm64.tar.gz"
      sha256 "92c9a6209720ca1cca4564574d679da4691fb1b9f65cf325dc317f66fc21370e"
      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfoutdated version")
  end
end
