# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfoutdated < Formula
  desc "Detect outdated Terraform modules and providers with breaking change analysis"
  homepage "https://github.com/AnassKartit/tfoutdated"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.2.0/tfoutdated_0.2.0_darwin_amd64.tar.gz"
      sha256 "28e72a28b620b4cc4652fbbdd00700cc73d5b3a8df3a15523b0866d5d831523d"

      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.2.0/tfoutdated_0.2.0_darwin_arm64.tar.gz"
      sha256 "a587790bc0a911acb481c7b3070b942e83a7a37bde7d9ab2fc1abee915f183d7"

      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.2.0/tfoutdated_0.2.0_linux_amd64.tar.gz"
      sha256 "85ecc800b464e3279cc15444d901bf402242f6865439da3a5a9b6d4dd40b5a8c"
      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.2.0/tfoutdated_0.2.0_linux_arm64.tar.gz"
      sha256 "da99690c65111a805a94019efc288db053f8e07fd27b8195559ed495e4ad1b78"
      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfoutdated version")
  end
end
