# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfoutdated < Formula
  desc "Detect outdated Terraform modules and providers with breaking change analysis"
  homepage "https://github.com/AnassKartit/tfoutdated"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.5.1/tfoutdated_0.5.1_darwin_amd64.tar.gz"
      sha256 "23fcbf1f33d5cabda40f06e1c26275caba3f6a797abb902938c960437a74351a"

      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.5.1/tfoutdated_0.5.1_darwin_arm64.tar.gz"
      sha256 "359da314c38b58e2fdf4b8ac726a780ffa5970232a59b8dee1f1fd17f626fb4b"

      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.5.1/tfoutdated_0.5.1_linux_amd64.tar.gz"
      sha256 "c403e367cbb700b11df2682123dccd34f869f289e4aae58b198aa3c9ca95af49"
      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.5.1/tfoutdated_0.5.1_linux_arm64.tar.gz"
      sha256 "342475db42bd9e5450c05405cbd5e6512fdd54899b2febe6d0941eb6df551c06"
      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfoutdated version")
  end
end
