# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfoutdated < Formula
  desc "Detect outdated Terraform modules and providers with breaking change analysis"
  homepage "https://github.com/AnassKartit/tfoutdated"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.3.0/tfoutdated_0.3.0_darwin_amd64.tar.gz"
      sha256 "5afc6d196790472cbdbef419f5011ce069007e81b30e1d2fae74abb154c15507"

      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.3.0/tfoutdated_0.3.0_darwin_arm64.tar.gz"
      sha256 "038dfaf5f2317db0c90dbc5c3dfb7f7f592b8d9fb2850b87ef27bc6bfe8fb11e"

      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.3.0/tfoutdated_0.3.0_linux_amd64.tar.gz"
      sha256 "6b8928a919b454541db07a17c18a3bb59bc0552f87fc7b0ab7d9ecab101316af"
      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AnassKartit/tfoutdated/releases/download/v0.3.0/tfoutdated_0.3.0_linux_arm64.tar.gz"
      sha256 "ed6e5b89cbdec85604528f6e8bbf4f8c9a9361d43aa73cf5998c1969ac6c53e5"
      define_method(:install) do
        bin.install "tfoutdated"
        bin.install "tfoutdated-mcp" if File.exist?("tfoutdated-mcp")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfoutdated version")
  end
end
